Add "skip" functionality with tests
Dzol/caffeine pull request #3
Opened 2018-04-17 14:04 UTC by sebb7

It allows to skip first elements of the stream. This feature can be helpful in orangeade application.

2018-04-20 17:04 UTC, Dzol requested changes
Thank you for this.

Would you mind running the formatter on the code here? I think it'll introduce a couple of line breaks. You can put `mix format --check-formatted` in the Travis configuration if you want otherwise I'll do it.

I really appreciate the property you already wrote. Would you also write a property to test that the same elements reside in the rest of the stream (in the same order)? `Enum.drop/2` would be nice for this.

2018-04-23 04:29 UTC, sebb7 commented
Hi @Dzol, 
I will take care of formatter and another property asap :)

2018-04-23 22:06 UTC, sebb7 commented
Hi @Dzol, 
Another test added. What do you think?

I have some questions about Travis because it is not set yet in caffeine. I know that I should add travis.yml file but what about build status and adding project to travis? I am able to add only my forked master. Should I do it and then make PR from my master? Or you are the only person to add travis to this project?

2018-04-24 08:36 UTC, Dzol commented on test/caffeine/stream_test.exs
> +      assert length(listify(t1)) == length(t2)
We need only `listify(t1) === t2` to assert that the very same values are in the stream and the original list

2018-04-24 08:38 UTC, Dzol commented
@sebb7 Oops: I meant Circle CI 😅

https://github.com/Dzol/caffeine/blob/master/.circleci/config.yml

2018-04-24 15:33 UTC, merged